_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 81
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: (12500)
  MAX_ITER: 13000
TEST:
  EVAL_PERIOD: 13000
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20
  PREV_CLASSES: (20, 20,)
  SCORE_THRESH: 0.16
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
