_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 21
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: ()
  MAX_ITER: 20000
TEST:
  EVAL_PERIOD: 20000
  PREV_INTRODUCED_CLS: 15
  CUR_INTRODUCED_CLS: 5
  PREV_CLASSES: (15,)
  MASK: 2
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
OUTPUT_DIR: "output/IOD_15_5/"
