_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 21
  NC_WEIGHT: 0.
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: ()
  MAX_ITER: 23000
TEST:
  EVAL_PERIOD: 23000
  PREV_INTRODUCED_CLS: 19
  CUR_INTRODUCED_CLS: 1
  PREV_CLASSES: (19,)
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
OUTPUT_DIR: "output/IOD_19_1/"
